id: PB519CD94
initial_creation_type: input
source_metadata:
  Title: Minor Buddhist Texts
  Editor: Tucci, G.
  Publisher: Motilal Banarsidas
  Place of Publication: Delhi
  Year: '1986'
  Caryāsaṅgrahapradīpaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:42:57.465097'
last_modified_at: '2022-03-08T16:42:57.465105'
